# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EtudiantUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from serverint import Ui_SerInt
from Server import Server
from PyQt5 import QtCore, QtGui, QtWidgets
import cv2

class Ui_Etuiant(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 516)
        
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 60, 81, 31))
        
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")


        """
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(450, 250, 71, 21))
        
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.setText("A9li dagui")
        """


        self.hostTextEdit = QtWidgets.QTextEdit(Form)
        self.hostTextEdit.setGeometry(QtCore.QRect(100, 60, 131, 31))
        self.hostTextEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:2px;")
        self.hostTextEdit.setObjectName("hostTextEdit")
        
        self.portTextEdit = QtWidgets.QTextEdit(Form)
        self.portTextEdit.setGeometry(QtCore.QRect(290, 60, 131, 31))
        self.portTextEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:2px;")
        self.portTextEdit.setObjectName("portTextEdit")
        
        self.connectButton = QtWidgets.QPushButton(Form)
        self.connectButton.setGeometry(QtCore.QRect(650, 60, 91, 31))
        self.connectButton.setObjectName("connectButton")
        self.connectButton.setStyleSheet("background-color:rgba(85,98,112,225);\n"
"color:rgba(255,255,255,255);\n"
"border-radius:5px;\n"
"")
        self.decButton = QtWidgets.QPushButton(Form)
        self.decButton.setGeometry(QtCore.QRect(650, 100, 95, 31))
        self.decButton.setObjectName("decoButton")
        self.decButton.setStyleSheet("background-color:rgba(85,98,112,225);\n"
"color:rgba(255,255,255,255);\n"
"border-radius:5px;\n"
"")




        
        
        # video
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)

        self.VideoButton = QtWidgets.QPushButton(Form)
        self.VideoButton.setFont(font)
        self.VideoButton.setGeometry(QtCore.QRect(450, 250, 71, 21))
        self.VideoButton.setObjectName("videoButton")
        self.VideoButton.setStyleSheet("background-color:rgba(85,98,112,225);\n"
"color:rgba(255,255,255,255);\n"
"border-radius:5px;\n"
"")





        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.messageBrowser = QtWidgets.QTextBrowser(Form)
        self.messageBrowser.setGeometry(QtCore.QRect(30, 150, 211, 251))
        self.messageBrowser.setObjectName("messageBrowser")
        self.msgTextEdit = QtWidgets.QTextEdit(Form)
        self.msgTextEdit.setGeometry(QtCore.QRect(30, 410, 211, 41))
        self.msgTextEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:2px;")
        self.msgTextEdit.setObjectName("msgTextEdit")
        # Send button
        self.sendButton = QtWidgets.QPushButton(Form)
        self.sendButton.setGeometry(QtCore.QRect(70, 460, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.sendButton.setStyleSheet("background-color:rgba(85,98,112,225);\n"
"color:rgba(255,255,255,255);\n"
"border-radius:5px;\n"
"")

        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(440, 60, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.nameTextEdit = QtWidgets.QTextEdit(Form)
        self.nameTextEdit.setGeometry(QtCore.QRect(490, 60, 131, 31))
        self.nameTextEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:2px;")
        self.nameTextEdit.setObjectName("nameTextEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        

        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Etudiant"))
        
        
        Form.setStyleSheet('background-color:white')
        self.label.setText(_translate("Form", "HostName:"))
        self.label_2.setText(_translate("Form", "Port:"))
        self.connectButton.setText(_translate("Form", "Connect"))
        self.decButton.setText(_translate("Form", "Deconnexion"))
        
        self.VideoButton.setText(_translate("Form","Video"))
        self.label_3.setText(_translate("Form", "Server tchat connection:"))
        self.label_4.setText(_translate("Form", "Tchat:"))
        self.sendButton.setText(_translate("Form", "Send"))
        self.label_5.setText(_translate("Form", "Name:"))

   
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
   
    ui = Ui_Etuiant()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
