# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ClientPrf import ClientPrf
from inscription import Ui_Inscription
from etudiant import Ui_Etuiant
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import sqlite3 as sqlite
from Client import Client
from Server import Server
import subprocess

class Ui_Form(object):

    def OpenWindow(self):
        #self.window = QtWidgets.QMainWindow()
        self.c = Client()
        #self.ui =
        #self.ui.setupUi(self.window)
        Form.hide()
        self.c.mainWindow.setWindowIcon(QtGui.QIcon('icone1.png'))
        self.c.mainWindow.show()  
    def OpenTeacherWindow(self):
            print("Connected to Teacher")
            self.prf = ClientPrf()
            Form.hide()
            self.prf.mainWindow.setWindowIcon(QtGui.QIcon('icone1.png'))
            self.prf.mainWindow.show() 

    def setupUi(self, Form):
               
        subprocess.Popen(args='python Server.py')
        Form.setObjectName("Form")
        Form.resize(616, 460)
        self.setIcon()
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 20, 590, 420))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"  background-color:rgba(85,98,112,225);\n"
"  color:rgba(255,255,255,255);\n"
"  border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(255,107,107,255);\n"
"  background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"  background-color:rgba(255,107,107,255);\n"
"}\n"
"QPushButton#pushButton_2{\n"
"  background-color:rgba(85,98,112,225);\n"
"  color:rgba(255,255,255,255);\n"
"  border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(255,107,107,255);\n"
"  background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"  background-color:rgba(255,107,107,255);\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(290, 40, 260, 341))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-radius:10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 25, 270, 360))
        self.label_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(169, 109,173, 1), stop:1 rgba(30, 139, 195, 1));\n"
"border-radius:10px;") 
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(330, 60, 90, 31))
        
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 110, 190, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 170, 190, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:7px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(340, 240, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(330, 300, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 330, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(50, 50, 200, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255,255,255,220);")
        self.label_5.setObjectName("label_5")

        self.label_pic = QtWidgets.QLabel(self.widget)
        pixmap = QtGui.QPixmap('icone1.png')
        self.label_pic.setPixmap(pixmap)
        #self.label_pic.setCentralWidget(label_pic)
        self.label_pic.setGeometry(70,160,220,250)
        #self.label_pic.resize(300, 300)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.LoginMethod)
        self.pushButton_2.clicked.connect(self.GoToCreateAcount)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FaceEMotionRecon"))
        self.label_3.setText(_translate("Form", "Se connecter"))
        self.label_3.update()
        self.lineEdit.setPlaceholderText(_translate("Form", "User Name"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "Login"))
        self.label_4.setText(_translate("Form", "Create new account:"))
        self.pushButton_2.setText(_translate("Form", "S'inscrire"))
        self.label_5.setText(_translate("Form", "Facial Emotion\nRecognition"))
    def LoginMethod(self):
            username = self.lineEdit.text()
            password = self.lineEdit_2.text()
            # Ouvrir la base de donnee
            connection = sqlite.connect('basdedonnees/database.db')
            # # Creation du cursor
            cursor = connection.cursor()
            # Etablir les rqts
            query_verify = "SELECT COUNT(*) FROM COMPTE WHERE USERNAME = \""+username+"\" AND mdp = \""+password+"\""
            query_account = "SELECT TYPE FROM COMPTE WHERE USERNAME = \""+username+"\""
            # Executer la requete
            cursor.execute(query_verify)
            nb = cursor.fetchone()[0]
            cursor.execute(query_account)
            type = cursor.fetchone()[0]

            if nb ==0:
                    print("Erreur compte introuvable")
                    msg = QtWidgets.QMessageBox()
                    msg.setIcon(QtWidgets.QMessageBox.Critical)
                    msg.setText("Username ou mot de passe incorrect")
                    msg.setWindowTitle("Error")
                    msg.exec_()
                    cursor.close()
                    connection.close()
            else:
                    if type == "etudiant":
                            print("Connected to student")
                            self.OpenWindow()
                    else:
                            print("Connected to Teacher")
                            self.OpenTeacherWindow()    


                    
                    
                    cursor.close()
                    connection.close()
                    
                   
                    
                    
    def GoToCreateAcount(self):
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_Inscription()
            self.window.setWindowIcon(QtGui.QIcon('icone1.png'))
            self.ui.setupUi(self.window)
           # Form.hide()
            self.window.show() 
    def setIcon(self):
             appIcon = QtGui.QIcon('icone1.png')
             Form.setWindowIcon(appIcon)
            



if __name__ == "__main__":
	app = QtWidgets.QApplication(sys.argv)
	Form = QtWidgets.QWidget()
	ui = Ui_Form()
	ui.setupUi(Form)
	Form.show()
	sys.exit(app.exec_())

