# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProfUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(671, 418)
        
        Form.setStyleSheet("background-color : white;")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(220, 60, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(380, 60, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.hostTextEdit = QtWidgets.QTextEdit(Form)
        self.hostTextEdit.setGeometry(QtCore.QRect(100, 60, 104, 31))
        self.hostTextEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:2px;")
        self.hostTextEdit.setObjectName("hostTextEdit")
        self.portTextEdit = QtWidgets.QTextEdit(Form)
        self.portTextEdit.setGeometry(QtCore.QRect(260, 60, 104, 31))
        self.portTextEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:2px;")
        self.portTextEdit.setObjectName("portTextEdit")
        self.nameTextEdit = QtWidgets.QTextEdit(Form)
        self.nameTextEdit.setGeometry(QtCore.QRect(430, 60, 104, 31))
        self.nameTextEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:2px;")
        self.nameTextEdit.setObjectName("nameTextEdit")
        self.connectButton = QtWidgets.QPushButton(Form)
        self.connectButton.setGeometry(QtCore.QRect(560, 50, 81, 31))
        self.connectButton.setStyleSheet("background-color:rgba(85,98,112,225);\n"
"color:rgba(255,255,255,255);\n"
"border-radius:5px;\n"
"")
        self.connectButton.setObjectName("connectButton")

        self.decButton = QtWidgets.QPushButton(Form)
        self.decButton.setGeometry(QtCore.QRect(560, 83, 90, 31))
        self.decButton.setStyleSheet("background-color:rgba(85,98,112,225);\n"
"color:rgba(255,255,255,255);\n"
"border-radius:5px;\n"
"")
        self.decButton.setObjectName("connectButton")
        self.sendButton = QtWidgets.QPushButton(Form)
        self.sendButton.setGeometry(QtCore.QRect(100, 260, 111, 31))
        self.sendButton.setStyleSheet("background-color:rgba(85,98,112,225);\n"
"color:rgba(255,255,255,255);\n"
"border-radius:5px;\n"
"")
        self.sendButton.setObjectName("sendButton")
        self.msgTextEdit = QtWidgets.QTextEdit(Form)
        self.msgTextEdit.setGeometry(QtCore.QRect(40, 190, 251, 41))
        self.msgTextEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0,200);\n"
"padding-bottom:2px;")
        self.msgTextEdit.setObjectName("msgTextEdit")
        self.messageBrowser = QtWidgets.QTextBrowser(Form)
        self.messageBrowser.setGeometry(QtCore.QRect(340, 140, 256, 271))
        self.messageBrowser.setObjectName("messageBrowser")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
       # self.label_5.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98,112, 255), stop:1 rgba(255, 107, 107, 255));\n"
#"border-radius:10px")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 311, 51))
        #self.label_7.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98,112, 255), stop:1 rgba(255, 107, 107, 255));\n"
#"border-radius:10px;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 130, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:black;")
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Prof"))
        self.label.setText(_translate("Form", "HostName:"))
        self.label_2.setText(_translate("Form", "Port:"))
        self.label_3.setText(_translate("Form", "Name:"))
        self.connectButton.setText(_translate("Form", "Connect"))
        self.decButton.setText(_translate("Form","Deconnexion"))
        self.sendButton.setText(_translate("Form", "Send"))
        self.label_6.setText(_translate("Form", "Tchat:"))
        self.label_4.setText(_translate("Form", "Server Connexion:"))


    

if __name__ == "__main__":
	app = QtWidgets.QApplication(sys.argv)
	Form = QtWidgets.QWidget()
	ui = Ui_Form()
	ui.setupUi(Form)
	Form.show()
	sys.exit(app.exec_())